language: generic

cache:
  timeout: 1000
  directories:
    - $HOME/.stack/
    - $HOME/.ghcjs/
    - $HOME/.local/bin/
    - $HOME/.cabal
    - .stack-work
    - build/backend/.stack-work/
    - luna-studio/.stack-work/
    - runner/.stack-work/

before_install:
# Download and unpack the stack executable
    - sudo apt-get update && sudo apt-get install -y software-properties-common openssh-client libzmq3-dev rpm2cpio
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - export PATH=`stack path --bin-path 2>/dev/null`:$PATH
    - stack setup
    - stack install hsc2hs
    - stack install happy
    - curl -o /tmp/luna-manager http://packages.luna-lang.org/linux/luna-manager
    - sudo mv /tmp/luna-manager /usr/bin
    - curl -o /tmp/packageConfig.yaml http://packages.luna-lang.org/linux/studio/packageConfig.yaml
    - sudo mv /tmp/packageConfig.yaml /home/travis/packageConfig.yaml
    - chmod +x /usr/bin/luna-manager



install:
    - "npm install -g npm"
    - "pip install requests"
 
script:
    - travis_wait 110 ./travis_build_backend.sh
