language: python

python: 3.6

cache:
  timeout: 1000
  directories:
    - $HOME/.stack/
    - $HOME/.ghcjs/
    - $HOME/.local/bin/
    - $HOME/luna/luna-studio/build/backend/.stack-work/
    - $HOME/luna/luna-studio/luna-studio/.stack-work/
    - $HOME/luna/luna-studio/runner/.stack-work/

before_install:
# Download and unpack the stack executable
    - sudo apt-get update && sudo apt-get install -y software-properties-common openssh-client libzmq3-dev rpm2cpio
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - export PATH=`stack path --bin-path 2>/dev/null`:$PATH
    - stack setup
    - stack install hsc2hs
    - stack install happy
    - curl -o /tmp/luna-manager http://packages.luna-lang.org/linux/luna-manager
    - sudo mv /tmp/luna-manager /usr/bin
    - curl -o /tmp/packageConfig.yaml http://packages.luna-lang.org/linux/studio/packageConfig.yaml
    - sudo mv /tmp/packageConfig.yaml /home/travis/packageConfig.yaml
    - chmod +x /usr/bin/luna-manager



install:
    - "npm install -g npm"
    - "pip install requests"

script:
    - stack build --stack-yaml=build/backend/stack.yaml --verbose --no-terminal --only-dependencies --install-ghc --test -j2 --ghc-options=-j2 --ghc-options=-O2 --ghc-options=\"+RTS -M3G -RTS\" +RTS -N1 -RTS
    - travis_wait stack build --stack-yaml=luna-studio/stack.yaml --no-terminal --only-dependencies --install-ghc --fast -j2 --ghc-options=-j2 --ghc-options=-O2
    - stack build --stack-yaml=runner/stack.yaml --only-dependencies --no-terminal --install-ghc --fast -j2 --ghc-options=-j2 --ghc-options=-O2
    - travis_wait stack build --stack-yaml build/backend/stack.yaml --no-terminal --copy-bins --no-run-tests --no-run-benchmarks -j2 --ghc-options=-j2 --ghc-options=-O2
    - travis_wait stack build --stack-yaml luna-studio/stack.yaml --no-terminal --fast -j2 --ghc-options=-j2
    - stack build --stack-yaml runner/stack.yaml --no-terminal --copy-bins --fast -j2 --ghc-options=-j2
    - luna-manager make-package /home/travis/packageConfig.yaml -v
